name: Pipeline-CI
on:
  push:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.4
      uses: shivammathur/setup-php@2.35.5
      with:
        php-version: 8.4
        extensions: mbstring,xml,ctype,iconv,intl,pdo,pdo_pgsql,dom,filter,gd

    - name: Check PHP version
      run: php -v

    - name: Cache
      uses: actions/cache@v4.3.0
      with:
        path: vendor
        key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

    - name: Install dependances
      run: composer install --no-interaction --no-progress





